language: go
sudo: required
addons:
  apt:
    packages:
    - lynx
    - jq
    - wget -q
    - grep
  hosts:
    - consul-vs.service.consul
go:
- '1.10'
before_script:
- sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
- pushd packer
- if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
- popd
- bash scripts/install_consul.sh
- bash scripts/install_vault.sh
- bash scripts/install_redis.sh
- bash scripts/install_SecretID_Factory.sh
- sudo cp /home/travis/.vault-token /usr/local/bootstrap/.vault-token
script:
- source ./var.env
- export REDIS_MASTER_IP=127.0.0.1
- export LEADER_IP=127.0.0.1
- sudo VAULT_ADDR=http://127.0.0.1:8200 vault status
- consul kv put "development/REDIS_MASTER_IP" "127.0.0.1"
- consul kv put "development/LEADER_IP" "127.0.0.1"
- bash scripts/travis_run_go_app.sh

